export const menuSections = [
  {
    id: 'porcoes',
    title: 'Porções',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=900&q=80',
    items: [
      { name: 'Bauru 1.0', description: 'Carne, mussarela, tomate e alface. Acompanha batata frita e molho da casa.', price: 22.9 },
      { name: 'Bauru 2.0', description: 'Carne, mussarela, tomate, alface, cheddar e bacon. Acompanha batata frita e molho da casa.', price: 26.9 },
      { name: 'Frango à Passarinho', description: '', price: 30 },
      { name: 'Calabresa Acebolada', description: 'Acompanha fatias de pão e molho da casa.', price: 33 },
    ],
  },
  {
    id: 'peixes',
    title: 'Peixes',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=900&q=80',
    items: [
      { name: 'Camarão Frito (400g)', description: '', price: 55 },
      { name: 'Iscas de Tilápia (450g)', description: '', price: 53 },
      { name: 'Filé de Porquinho Empanado (450g)', description: '', price: 53 },
      { name: 'Almofadinha de Tilápia', description: 'Massa de mandioca e recheio de tilápia desfiada com molho.', price: 37 },
    ],
  },
  {
    id: 'porcoes-fritas',
    title: 'Porções Fritas',
    image: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=900&q=80',
    items: [
      { name: 'Coxinha de Frango (20 un)', description: '', price: 26 },
      { name: 'Bolinha de Queijo (20 un)', description: '', price: 26 },
      { name: 'Risoles (presunto e queijo, 20 un)', description: '', price: 26 },
      { name: 'Croquete de Carne (20 un)', description: '', price: 26 },
      { name: 'Mini Pastéis Sortidos (20 un)', description: 'Carne, queijo e frango.', price: 35 },
      { name: 'Batata Frita (500g)', description: '', price: 25 },
      { name: 'Batata Frita c/ Mussarela (500g)', description: '', price: 33 },
      { name: 'Batata Frita c/ Cheddar (500g)', description: '', price: 30 },
      { name: 'Batata Frita c/ Mussarela e Bacon (500g)', description: '', price: 39 },
      { name: 'Batata Frita c/ Cheddar e Bacon (500g)', description: '', price: 35 },
      { name: 'Polenta Recheada Provolone com Rúcula', description: '', price: 35 },
      { name: 'Polenta Recheada Costela com Provolone', description: '', price: 35 },
    ],
  },
  {
    id: 'porcao-premium',
    title: 'Porção Premium',
    image: 'https://images.unsplash.com/photo-1615937691194-97dbd3f3dc29?w=900&q=80',
    items: [
      { name: 'Panceta Empanada (400g)', description: '', price: 45 },
      { name: 'Camarão Empanado c/ Catupiry (12 un)', description: '', price: 55 },
      { name: 'Bolinho de Costela c/ Gorgonzola (12 un)', description: '', price: 43 },
      { name: 'Bolinho Cambotia c/ Carne Seca (12 un)', description: '', price: 43 },
    ],
  },
  {
    id: 'frios',
    title: 'Frios',
    image: 'https://images.unsplash.com/photo-1626200926749-1663078a2ee2?w=900&q=80',
    items: [
      { name: 'Salame (100g)', description: '', price: 16 },
      { name: 'Azeitona (concha)', description: '', price: 4 },
      { name: 'Mussarela (100g)', description: '', price: 9 },
      { name: 'Presunto (100g)', description: '', price: 7 },
      { name: 'Salsicha Conserva (un.)', description: '', price: 4 },
      { name: 'Batata Conserva (un.)', description: '', price: 1 },
      { name: 'Cebola Conserva (un.)', description: '', price: 1 },
      { name: 'Queijo Palito (un.)', description: '', price: 5 },
      { name: 'Ovo de Codorna (un.)', description: '', price: 1 },
    ],
  },
  {
    id: 'caipirinhas',
    title: 'Caipirinhas',
    image: 'https://images.unsplash.com/photo-1541591425126-4e6cc7e18785?w=900&q=80',
    groups: [
      {
        name: 'Pinga',
        items: [
          { name: 'Caipirinha Limão', description: '', price: 13 },
          { name: 'Abacaxi, Abacaxi c/ Hortelã, Maracujá ou Morango', description: '', price: 16 },
        ],
      },
      {
        name: 'Vodka',
        items: [
          { name: 'Caipiroska Limão', description: '', price: 16 },
          { name: 'Abacaxi, Abacaxi c/ Hortelã, Maracujá ou Morango', description: '', price: 20 },
        ],
      },
      {
        name: 'Vinho',
        items: [
          { name: 'Caipivinho Limão', description: '', price: 15 },
          { name: 'Espanhola', description: '', price: 17 },
        ],
      },
      {
        name: 'Rum',
        items: [
          { name: 'Caipirum Limão', description: '', price: 16 },
          { name: 'Abacaxi, Abacaxi c/ Hortelã, Maracujá ou Morango', description: '', price: 20 },
        ],
      },
      {
        name: 'Gin',
        items: [
          { name: 'Caipigin Limão', description: '', price: 16 },
          { name: 'Abacaxi, Abacaxi c/ Hortelã, Maracujá ou Morango', description: '', price: 20 },
        ],
      },
      {
        name: 'Steinhaeger Becosa',
        items: [
          { name: 'Caipiroska Limão', description: '', price: 16 },
          { name: 'Abacaxi, Abacaxi c/ Hortelã, Maracujá ou Morango', description: '', price: 20 },
        ],
      },
    ],
  },
  {
    id: 'drinks',
    title: 'Drinks',
    image: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=900&q=80',
    items: [
      { name: 'Gin Tônica (ou Schweppes)', description: '', price: 15 },
      { name: 'Campari Citrus', description: 'Schweppes ou tônica.', price: 18 },
      { name: 'Tchay', description: 'Smirnoff, Monster/Red Bull. Sabores: morango, maracujá, cereja, céu azul.', price: 25 },
      { name: 'Tchay Passport', description: 'Passport, red bull e gelo de coco. Opção c/ 2 doses R$ 35,00.', price: 28 },
      { name: 'Tchay Malibu', description: '2 doses malibu, red bull, gelo de coco.', price: 40 },
      { name: 'Tchay Red Label', description: 'Red label, red bull, gelo de coco. Opção c/ 2 doses R$ 45,00.', price: 30 },
      { name: "Tchay Jack Daniel's Tradicional / Honey / Black", description: 'Dose, red bull, gelo de coco. Opção c/ 2 doses R$ 60,00.', price: 40 },
    ],
  },
  {
    id: 'whisky-licor',
    title: 'Whisky e Licor',
    image: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=900&q=80',
    items: [
      { name: "Jack Daniel's", description: '', price: 20 },
      { name: "Jack Daniel's Honey", description: '', price: 20 },
      { name: 'Red Label', description: '', price: 15 },
      { name: 'Black Label', description: '', price: 25 },
      { name: 'Passport', description: '', price: 10 },
      { name: 'Licor 43', description: '', price: 25 },
    ],
  },
  {
    id: 'cachaca-sabores',
    title: 'Cachaça Sabores',
    image: 'https://images.unsplash.com/photo-1608885898957-a559228e8749?w=900&q=80',
    items: [
      { name: 'Gabriela', description: '', price: 6 },
      { name: 'Mel com Amburana', description: '', price: 6 },
      { name: 'Pêssego', description: '', price: 6 },
      { name: 'Melzinho', description: '', price: 6 },
      { name: 'Morango do Amor', description: '', price: 6 },
      { name: 'Café', description: '', price: 6 },
      { name: 'Canela', description: '', price: 6 },
      { name: 'Caju', description: '', price: 6 },
      { name: 'Rapadura', description: '', price: 6 },
    ],
  },
  {
    id: 'vinho-taca',
    title: 'Vinho Taça',
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=900&q=80',
    items: [
      { name: 'Pérgola', description: '', price: 15 },
      { name: 'Goes Tradições', description: '', price: 15 },
    ],
  },
  {
    id: 'doses',
    title: 'Doses',
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=900&q=80',
    items: [
      { name: 'José Cuervo', description: '', price: 15 },
      { name: 'Tequiloka', description: '', price: 8 },
      { name: 'Seleta', description: '', price: 8 },
      { name: 'Boazinha', description: '', price: 8 },
      { name: 'São Francisco', description: '', price: 8 },
      { name: 'Ypioca', description: '', price: 6 },
      { name: 'Campari', description: '', price: 10 },
      { name: 'Cynar', description: '', price: 7 },
      { name: 'Paratudo', description: '', price: 5 },
      { name: 'Paizano', description: '', price: 5 },
      { name: '51', description: '', price: 3 },
      { name: 'Vila Velha', description: '', price: 3 },
      { name: 'Velho Barreiro', description: '', price: 3 },
      { name: 'Presidente', description: '', price: 6 },
      { name: 'Dreher', description: '', price: 6 },
      { name: 'São João da Barra', description: '', price: 6 },
      { name: 'Domecq', description: '', price: 8 },
      { name: 'Conhaque Comel', description: '', price: 6 },
      { name: 'Smirnoff', description: '', price: 8 },
      { name: 'Underberg', description: '', price: 8 },
      { name: 'Jurubeba', description: '', price: 5 },
      { name: 'Malibu', description: '', price: 12 },
      { name: 'Catuaba', description: '', price: 5 },
      { name: 'Steinhaeger', description: '', price: 8 },
    ],
  },
  {
    id: 'cervejas-litro',
    title: 'Cervejas Litro',
    image: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?w=900&q=80',
    items: [
      { name: 'Antarctica', description: '', price: 12.9 },
      { name: 'Brahma', description: '', price: 12.9 },
      { name: 'Skol', description: '', price: 12.9 },
      { name: 'Budweiser', description: '', price: 13.9 },
      { name: 'Duplo Malte (Brahma)', description: '', price: 13.9 },
    ],
  },
  {
    id: 'cervejas-lata',
    title: 'Cervejas Lata',
    image: 'https://images.unsplash.com/photo-1613743983303-b3e89f8968eb?w=900&q=80',
    items: [
      { name: 'Antarctica', description: '', price: 6 },
      { name: 'Brahma', description: '', price: 6 },
      { name: 'Skol', description: '', price: 6 },
      { name: 'Império', description: '', price: 6 },
      { name: 'Original', description: '', price: 7 },
      { name: 'Skol Latão', description: '', price: 8 },
    ],
  },
  {
    id: 'cervejas-300',
    title: 'Cervejas 300ml',
    image: 'https://images.unsplash.com/photo-1618183479302-1e0aa382c36b?w=900&q=80',
    items: [
      { name: 'Antarctica', description: '', price: 5 },
      { name: 'Brahma', description: '', price: 5 },
      { name: 'Skol', description: '', price: 5 },
      { name: 'Original', description: '', price: 6 },
      { name: 'Budweiser', description: '', price: 6 },
    ],
  },
  {
    id: 'cervejas-600',
    title: 'Cervejas 600ml',
    image: 'https://images.unsplash.com/photo-1600788907416-456578634209?w=900&q=80',
    items: [
      { name: 'Antarctica', description: '', price: 10.9 },
      { name: 'Brahma', description: '', price: 10.9 },
      { name: 'Skol', description: '', price: 10.9 },
      { name: 'Império', description: '', price: 10.9 },
      { name: 'Amstel', description: '', price: 11.9 },
      { name: 'Budweiser', description: '', price: 11.9 },
      { name: 'Original', description: '', price: 13.5 },
      { name: 'Spaten', description: '', price: 13 },
      { name: 'Stella', description: '', price: 16 },
      { name: 'Heineken', description: '', price: 16 },
      { name: 'Corona', description: '', price: 16 },
    ],
  },
  {
    id: 'long-neck',
    title: 'Long Neck',
    image: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?w=900&q=80',
    items: [
      { name: 'Heineken', description: '', price: 10 },
      { name: 'Heineken Zero', description: '', price: 10 },
      { name: 'Corona', description: '', price: 10 },
      { name: 'Budweiser', description: '', price: 9 },
      { name: 'Budweiser Zero', description: '', price: 9 },
      { name: 'Stella', description: '', price: 10 },
      { name: 'Amstel Ultra', description: '', price: 10 },
      { name: 'Skol Beats', description: '', price: 12 },
      { name: 'Smirnoff Ice', description: '', price: 12 },
    ],
  },
  {
    id: 'sem-alcool',
    title: 'Refrigerantes, Sucos e Água',
    image: 'https://images.unsplash.com/photo-1437418747212-8d9709afab22?w=900&q=80',
    groups: [
      {
        name: 'Refrigerante Lata',
        items: [
          { name: 'Coca-Cola', description: '', price: 6 },
          { name: 'Coca-Cola Zero', description: '', price: 6 },
          { name: 'Fanta Laranja', description: '', price: 6 },
          { name: 'Fanta Uva', description: '', price: 6 },
          { name: 'Sprite', description: '', price: 6 },
        ],
      },
      {
        name: 'Refrigerante Litro',
        items: [{ name: 'Coca-Cola 1 Litro', description: '', price: 8 }],
      },
      {
        name: 'Suco Lata',
        items: [{ name: 'Del Valle', description: 'Uva, pêssego ou maracujá.', price: 6 }],
      },
      {
        name: 'Sucos',
        items: [
          { name: 'Laranja c/ Acerola', description: '', price: 7 },
          { name: 'Abacaxi', description: '', price: 7 },
          { name: 'Abacaxi c/ Hortelã', description: '', price: 7 },
          { name: 'Morango', description: '', price: 7 },
          { name: 'Morango c/ Leite', description: '', price: 8.5 },
          { name: 'Maracujá', description: '', price: 8 },
          { name: 'Maracujá c/ Leite', description: '', price: 8.5 },
        ],
      },
      {
        name: 'Água e Outros',
        items: [
          { name: 'Água s/ Gás', description: '', price: 3 },
          { name: 'Água c/ Gás', description: '', price: 4 },
          { name: 'Água Tônica', description: '', price: 6 },
          { name: 'H2O Limão', description: '', price: 6 },
          { name: 'H2O Limoneto', description: 'Gelo e limão + R$ 1,00.', price: 7 },
        ],
      },
      {
        name: 'Energético Lata',
        items: [
          { name: 'Monster', description: '', price: 14 },
          { name: 'Red Bull', description: '', price: 14 },
        ],
      },
    ],
  },
]
